project_id = "mvzssjyzbwccioqvhjpo"

[functions.send-lead-notification]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.check-follow-up-reminders]
verify_jwt = false
